### PR TITLE
template: specify priority class

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
This PR specifies the deployment's priority class, thus assuring the component is not preempted for other workloads with lesses priority. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Specify the kubevirt-cluster-critical priorityClass for this deployment. It requires KubeVirt to be deployed.
```

### CODE REVIEW

**Review by oshoval — COMMENTED** [review]
what happen if someone tries to deploy it without kubevirt ?
(and the PC doesnt exists)
well he cant anyhow because it listens to VM / VMI i guess so it is non issue

**Comment by maiqueb** [comment]
> what happen if someone tries to deploy it without kubevirt ? (and the PC doesnt exists) well he cant anyhow because it listens to VM / VMI i guess so it is non issue

Yeah, that's kind of the point ... This is a project in the kubevirt org ... 

I guess we should add to the docs a note indicating this must be used w/ kubevirt.

Let me check what happens though ...

**Comment by oshoval** [comment]
Please dont over invest on that, it also happens on KubeSecondaryDNS, and we concluded there it is fine
release note is more than enough imho

**Comment by oshoval** [comment]
btw are you sure you want to use this pc ?
i remember that we used the system critical pc and the other one that k8s gives for the components (forgot the name),
we considered components that are mandatory for kubevirt to have higher prio than kubevirt
if it was a DS it was highest prio pc, 
if it was a Deployment that could be on any node, it was the one below that, but higher than kubevirt
Petr was in the loop, in case i am wrong

**Comment by maiqueb** [comment]
> btw are you sure you want to use this pc ? i remember that we used `system-node-critical` and `system-node-critical` built in pcs for sig network components.
> 
> We considered components that are mandatory for kubevirt to have higher prio than kubevirt, if it was a DaemonSet it was highest prio pc, system-critical if it was a Deployment that could be on any node, it was node-critical Petr was in the loop, in case i am wrong

So you're suggesting we use `system-node-critical` instead ?

**Comment by oshoval** [comment]
yes, wdyt?
if you want to make sure Petr is best with that

**Comment by phoracek** [comment]
For a deployment that other components relay on, use cluster critical. We don't have to be node critical - it is ok if the pod moves to a different node.

**Comment by phoracek** [comment]
@oshoval 

> We considered components that are mandatory for kubevirt to have higher prio than kubevirt, if it was a DaemonSet it was highest prio pc, system-critical if it was a Deployment that could be on any node, it was node-critical Petr was in the loop, in case i am wrong

I don't remember / understand this. Why would we set node critical for a deployment?

**Comment by oshoval** [comment]
I have a typo there / mix

I remember there are 2 classes, highest which is only for stuff that should be all on nodes
and one below that just need to be one stuff like Deployment that are allowed to switch but critical to have, such as KMP
forgot who is who

**Comment by maiqueb** [comment]
@oshoval please take another look

**Comment by oshoval** [comment]
Nit:
Release note: "It requires KubeVirt to be deployed." still true but not due to the PC / this PR
Thanks

**Pull request merged**
