### PR TITLE
cluster: Use --opt-out-kv-ipam

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Make cluster-sync going to install it anyhow.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by oshoval** [comment]
```
#8 13.85 >>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xFailed to download metadata (metalink: "https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64") for repository "rawhide"
#8 13.85  Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
some hiccup while dnf install

**Comment by oshoval** [comment]
https://pagure.io/fedora-infrastructure/issue/12183
Fedora issue here

**Comment by oshoval** [comment]
interesting, flake on unit test
i think it is not related to this PR, as it changes only e2e

**Comment by maiqueb** [comment]
> interesting, flake on unit test (unless something was changed and it will fail consistently) https://github.com/kubevirt/ipam-extensions/actions/runs/10900433841/job/30248013978?pr=68 i think it is not related to this PR, as it changes only e2e

Hm, it's the order right ? Do we really need the order of this to be this static ? 
If not, we can just use consist of instead of equal in the tests.
@qinqon

**Comment by qinqon** [comment]
> > interesting, flake on unit test (unless something was changed and it will fail consistently) https://github.com/kubevirt/ipam-extensions/actions/runs/10900433841/job/30248013978?pr=68 i think it is not related to this PR, as it changes only e2e
> 
> Hm, it's the order right ? Do we really need the order of this to be this static ? If not, we can just use consist of instead of equal in the tests. @qinqon

We are not crafting the jsonpatch ourselves, we just pass new and old pods to `admission.PatchResponseFromRaw` so this is supose to be fine, problem is that at slices order matter when we compare things at tests, even if we compare them as a json.

We have to fix the test so the test case instruct to ignore the order there.

**Pull request merged**
